# caddyv2-upload

This repo holds a simple caddyserver v2 upload handler

WARNING: You have to secure the upload URL as the nature of
  this handler/plugin is to save uploaded artifacts on the disc.

In this handler are the following modules in use.

* templates
* file_server
* github.com/caddyserver/jsonc-adapter
* upload :-)

## Configuration

### Parameters

[cols="2,6",options=header]
|===
|Name
|Description

|**dest_dir**
|The directory in which the files will be uploaded

|**response_template**
|The response template after a upload was successfully

|**max_size**
|is the maximum size in bytes allowed for the upload.
  It accepts all size values supported by https://pkg.go.dev/github.com/dustin/go-humanize#pkg-constants[go-humanize]. Reads of 
  more bytes will return an error with HTTP status 413.

|**notify_url**
|After a successful upload will this URL be called. The only supported schema is **https**.

|**notify_method**
|The default method is `GET`. If you need to make a `POST` request please open a feature issue
  as for now is a request body handling not implemented

|**insecure**
|This boolean flag configure the `InsecureSkipVerify` in the  https://pkg.go.dev/crypto/tls#Config[tls-config] .
  Default is false which implies that a valid CA must be used

|**capath**
|This is the Parameter where you can define the CA for the **notify_url**.
|===

### JSON

Because I prefer the https://caddyserver.com/docs/json/[JSON Config ] 
will I write here the config in JSON Syntax.

[source,json]
----

                {
                  "handler": "upload",
                  "dest_dir": "tmp-upl",   # <1>
                  "max_filesize": 2048,    # <2>
                  "response_template":"upload-resp-template.txt" # <3>
                },
----
<1> Destination Directory on the Server site
<2> Maximal possible upload size
<3> the response template which will be used for response after upload

A full working example is in 
`docker-files/opt/webroot/config/Caddyfile-upload.json`

### Caddyfile

Here a example Caddyfile which expects that the environment variable
`APPPORT` is set.

[source]
----
{
	order upload before file_server
}

{$APPPORT} {
	root .

	file_server browse
	templates

	@mypost method POST
	upload @mypost {
		dest_dir tmp-upl
		max_filesize 4MB
		response_template templates/upload-resp-template.txt
	}

	log {
		output file access.log
	}
}
----

## build

[source,shell]
---
xcaddy build --with github.com/kirsch33/realip \
  --with github.com/caddyserver/jsonc-adapter \
  --with github.com/git001/caddyv2-upload
---

## run

### cli

[source,shell]
---
APPPORT=:2011 ./caddy run \
  -adapter jsonc \
  -config Caddyfile-upload.json 
---

### docker

You can get this image from docker hub

The default listen port must be defined with this variable

`APPPORT=:2011`

https://hub.docker.com/r/me2digital/caddyv2-upload

[source,shell]
---
podman run --rm --network host --name caddy-test \
  --env APPPORT=:8888 -it \
  docker.io/me2digital/caddyv2-upload:latest
# or 
docker run --name caddy-test --rm \
  docker.io/me2digital/caddyv2-upload:latest
---

## example cli

When you run the Image with port 8888 can you use curl or any other
tool to post (upload) files

It's not necessary to use `-X POST` as written in this Blog post
https://daniel.haxx.se/blog/2015/09/11/unnecessary-use-of-curl-x/[UNNECESSARY USE OF CURL -X]


Here a example call with curl

[source,shell]
----
curl -v --form myFile=@README.adoc http://localhost:8888/templates/upload-template.html
*   Trying 127.0.0.1:8888...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8888 (#0)
> POST /templates/upload-template.html HTTP/1.1
> Host: localhost:8888
> User-Agent: curl/7.68.0
> Accept: */*
> Content-Length: 2492
> Content-Type: multipart/form-data; boundary=------------------------58b770bc61c0e691
> Expect: 100-continue
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 100 Continue
* We are completely uploaded and fine
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Content-Length: 299
< Etag: "rbb1gx8b"
< Last-Modified: Tue, 03 May 2022 11:34:09 GMT
< Server: Caddy
< Date: Thu, 19 May 2022 21:45:07 GMT
< 

http.request.uri.path: {{placeholder "http.request.uri.path"}}

http.request.uuid {{placeholder "http.request.uuid" }}
http.request.host {{placeholder "http.request.host" }}

http.upload.filename: {{placeholder "http.upload.filename"}}
http.upload.filesize: {{placeholder "http.upload.filesize"}}
----