# caddyv2-upload

This repo holds a simple  caddyserver v2 upload handler

WARNING: You have to secure the upload URL as the nature of
  this handler/plugin is to save uploaded artifacts on the disc.

In this handler are the following modules in use.

* templates
* file_server
* github.com/caddyserver/jsonc-adapter
* upload :-)

# config

**max_size** is the maximum size in bytes allowed for the upload.
  It accepts all size values supported by https://pkg.go.dev/github.com/dustin/go-humanize#pkg-constants[go-humanize]. Reads of 
  more bytes will return an error with HTTP status 413.

Because I prefer the https://caddyserver.com/docs/json/[JSON Config ] 
will I write here the config only in JSON Syntax.

[source,json]
----

                {
                  "handler": "upload",
                  "dest_dir": "tmp-upl",   # <1>
                  "max_filesize": 2048,    # <2>
                  "response_template":"upload-resp-template.txt" # <3>
                },
----
<1> Destination Directory on the Server site
<2> Maximal possible upload size
<3> the response template which will be used for respose after upload

A full working example is in 
`docker-files/opt/webroot/config/Caddyfile-upload.json`

## Caddyfile

Here a example Caddyfile

[source]
----
{
	order upload before file_server
}

:8888 {
	root * /var/test

	file_server /var/test/* {
		browse /var/test/upload_index.htm
	}

	upload {
		dest_dir /var/test/tmp_upload
		max_filesize 4MB
	}

	log {
		output file access.log
	}
}
----
# build

[source,shell]
---
xcaddy build --with github.com/kirsch33/realip \
  --with github.com/caddyserver/jsonc-adapter \
  --with github.com/git001/caddyv2-upload
---

# run

## cli

[source,shell]
---
APPPORT=:2011 ./caddy run \
  -adapter jsonc \
  -config Caddyfile-upload.json 
---

## docker

You can get this image from docker hub

The default listen port is defined with this variable

`APPPORT=:2011`

https://hub.docker.com/r/me2digital/caddyv2-upload

[source,shell]
---
podman run --rm docker.io/me2digital/caddyv2-upload:0.1
# or 
docker run --rm docker.io/me2digital/caddyv2-upload:0.1
---